name: is_pirated
description: Check if your app is installed from an unauthorised source
version: 0.1.0
homepage:
repository:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  url_launcher: ^6.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sethusenthil.is_pirated
        pluginClass: IsPiratedPlugin
      ios:
        pluginClass: IsPiratedPlugin
