name: is_pirated
description: Check and handle if your app is installed from an unauthorized source. Provides tolling to auto terminate app & open store listing
version: 0.2.0
homepage: https://github.com/SethuSenthil/is-pirated
repository: https://github.com/SethuSenthil/is-pirated

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  url_launcher: ^6.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sethusenthil.is_pirated
        pluginClass: IsPiratedPlugin
      ios:
        pluginClass: IsPiratedPlugin
